<?php

/**
 * Default error page.
 */

namespace Tracy;

?>
<!DOCTYPE html>
<meta charset="utf-8">
<meta name=robots content=noindex>
<meta name=generator content="Tracy">
<script>document.body.innerHTML = ''</script>
<style>
	body { color: #333; background: white; width: 500px; margin: 100px auto }
	h1 { font: bold 47px/1.5 sans-serif; margin: .6em 0 }
	p { font: 21px/1.5 Georgia,serif; margin: 1.5em 0 }
	small { font-size: 70%; color: gray }
</style>

<title>Interní chyba serveru</title>

<h1>Interní chyba serveru</h1>

<p>Omlouváme se! Došlo k interní chybě na serveru. Situaci se snažíme vyhodnotit a opravit co nejdříve. Zkuste to za chvíli, děkujeme za pochopení!</p>

<p><small>chyba 500</small></p>
